<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="DesembolsosControllerTest" tests="7" time="0.096157123" failures="6" errors="1" skipped="0" assertions="6" timestamp="2014-12-02T21:58:28-05:00">
  <testcase name="test_should_create_desembolso" time="0.043338048" assertions="1">
    <failure type="Minitest::Assertion" message="&quot;Desembolso.count&quot; didn't change by 1....">
"Desembolso.count" didn't change by 1.
Expected: 3
  Actual: 2 (Minitest::Assertion)
/home/gustavo/repos/rails/modulo_seguimiento/implementacion/test/controllers/desembolsos_controller_test.rb:21    </failure>
  </testcase>
  <testcase name="test_should_destroy_desembolso" time="0.01087778" assertions="1">
    <failure type="Minitest::Assertion" message="&quot;Desembolso.count&quot; didn't change by -1....">
"Desembolso.count" didn't change by -1.
Expected: 1
  Actual: 2 (Minitest::Assertion)
/home/gustavo/repos/rails/modulo_seguimiento/implementacion/test/controllers/desembolsos_controller_test.rb:60    </failure>
  </testcase>
  <testcase name="test_should_get_edit" time="0.007142662" assertions="1">
    <failure type="Minitest::Assertion" message="Expected response to be a &lt;success&gt;, but was &lt;302&gt;">
Expected response to be a &lt;success&gt;, but was &lt;302&gt; (Minitest::Assertion)
/home/gustavo/repos/rails/modulo_seguimiento/implementacion/test/controllers/desembolsos_controller_test.rb:43    </failure>
  </testcase>
  <testcase name="test_should_get_index" time="0.008661651" assertions="1">
    <failure type="Minitest::Assertion" message="Expected response to be a &lt;success&gt;, but was &lt;302&gt;">
Expected response to be a &lt;success&gt;, but was &lt;302&gt; (Minitest::Assertion)
/home/gustavo/repos/rails/modulo_seguimiento/implementacion/test/controllers/desembolsos_controller_test.rb:11    </failure>
  </testcase>
  <testcase name="test_should_get_new" time="0.006134087" assertions="1">
    <failure type="Minitest::Assertion" message="Expected response to be a &lt;success&gt;, but was &lt;302&gt;">
Expected response to be a &lt;success&gt;, but was &lt;302&gt; (Minitest::Assertion)
/home/gustavo/repos/rails/modulo_seguimiento/implementacion/test/controllers/desembolsos_controller_test.rb:17    </failure>
  </testcase>
  <testcase name="test_should_show_desembolso" time="0.00731329" assertions="1">
    <failure type="Minitest::Assertion" message="Expected response to be a &lt;success&gt;, but was &lt;302&gt;">
Expected response to be a &lt;success&gt;, but was &lt;302&gt; (Minitest::Assertion)
/home/gustavo/repos/rails/modulo_seguimiento/implementacion/test/controllers/desembolsos_controller_test.rb:38    </failure>
  </testcase>
  <testcase name="test_should_update_desembolso" time="0.006770131" assertions="0">
    <error type="ActionController::UrlGenerationError" message="ActionController::UrlGenerationError: No route matches {:action=&gt;&quot;show&quot;, :controller=&gt;&quot;desembolsos&quot;, :id=&gt;nil} missing required keys: [:id]...">
ActionController::UrlGenerationError: No route matches {:action=&gt;"show", :controller=&gt;"desembolsos", :id=&gt;nil} missing required keys: [:id]
    test/controllers/desembolsos_controller_test.rb:56:in `block in &lt;class:DesembolsosControllerTest&gt;' (ActionController::UrlGenerationError)
/home/gustavo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:192    </error>
  </testcase>
</testsuite>
